/**
 * One-shot migration/traceability tool.
 *
 * The legacy CSV (data/drug-prescription.csv) is NOT application data any more —
 * the curated knowledge base in content/ is the single source of truth. This
 * script exists only to keep a record of *where the curated condition↔remedy
 * links came from*: it maps every distinct (condition, severity, drug-string)
 * row in the legacy CSV onto a canonical remedy id in content/remedies.json
 * (matched by canonicalName / aliases), and writes content/PROVENANCE.md.
 *
 * Run: npm run kb:ingest
 *
 * If it reports UNMAPPED legacy strings, a canonical remedy alias is missing —
 * add the legacy spelling to that remedy's `aliases` in content/remedies.json.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const csvPath = resolve(root, "data/drug-prescription.csv");
const remediesPath = resolve(root, "content/remedies.json");
const outPath = resolve(root, "content/PROVENANCE.md");

const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

// ---- legacy CSV: columns are condition,age,gender,severity,drug (no header)
const rows = readFileSync(csvPath, "utf8")
  .split(/\r?\n/)
  .filter(Boolean)
  .map((line) => {
    // legacy columns: condition, age, gender, severity, drug — age & gender dropped
    const [condition, , , severity, ...drug] = line.split(",");
    return { condition: norm(condition), severity: norm(severity), drug: drug.join(",").trim() };
  });

const SEVERITY_MAP = { low: "mild", normal: "moderate", high: "severe" };

/**
 * Legacy drug strings deliberately NOT migrated, with the reason. These are
 * not remedies: "laxative" is a generic drug class, "phadke" is an
 * unidentifiable proprietary/name entry.
 */
const KNOWN_DROPPED = {
  laxative: "Generic drug class, not a specific Ayurvedic remedy.",
  phadke: "Unidentifiable legacy entry (proprietary name or data error).",
};

// ---- canonical remedies: name + aliases -> id
const remedies = JSON.parse(readFileSync(remediesPath, "utf8")).remedies;
const lookup = new Map();
for (const r of remedies) {
  for (const key of [r.canonicalName, r.id, ...r.aliases]) lookup.set(norm(key), r.id);
}

// ---- distinct (condition, severity, drug) tuples
const seen = new Set();
const mapped = [];
const unmapped = new Map();
for (const { condition, severity, drug } of rows) {
  const key = `${condition}|${severity}|${drug}`;
  if (seen.has(key)) continue;
  seen.add(key);
  const remedyId = lookup.get(norm(drug));
  if (remedyId) {
    mapped.push({ condition, severity: SEVERITY_MAP[severity] ?? severity, drug, remedyId });
  } else if (norm(drug) in KNOWN_DROPPED) {
    // deliberately not migrated — reported separately, not an error
  } else {
    unmapped.set(norm(drug), (unmapped.get(norm(drug)) ?? 0) + 1);
  }
}

// ---- report
const byCondition = {};
for (const m of mapped) {
  (byCondition[m.condition] ??= new Map()).set(m.remedyId, m);
}

let md = `# Provenance — legacy CSV → curated knowledge base

_Generated by \`npm run kb:ingest\`. Do not edit by hand._

The file \`data/drug-prescription.csv\` is **frozen legacy input**. It is not
read at runtime and the engine does not depend on it. This table records which
curated remedy each legacy \`(condition, severity, drug-string)\` row was folded
into during migration.

Legacy severity labels \`LOW / NORMAL / HIGH\` were mapped to \`mild / moderate /
severe\`. Legacy \`age\` and \`gender\` columns were **dropped**: inspection of the
CSV showed the remedy never varied with gender, and the age grid was arbitrary
rather than clinically meaningful.

`;

for (const condition of Object.keys(byCondition).sort()) {
  md += `## ${condition[0].toUpperCase()}${condition.slice(1)}\n\n`;
  md += `| legacy drug string(s) | legacy severity | canonical remedy id |\n|---|---|---|\n`;
  const rowsForCond = mapped.filter((m) => m.condition === condition);
  const grouped = new Map();
  for (const m of rowsForCond) {
    const g = grouped.get(m.remedyId) ?? { drugs: new Set(), sev: new Set() };
    g.drugs.add(m.drug);
    g.sev.add(m.severity);
    grouped.set(m.remedyId, g);
  }
  for (const [remedyId, g] of [...grouped].sort()) {
    md += `| ${[...g.drugs].join(", ")} | ${[...g.sev].join(", ")} | \`${remedyId}\` |\n`;
  }
  md += `\n`;
}

md += `## Deliberately not migrated\n\n`;
for (const [s, reason] of Object.entries(KNOWN_DROPPED)) md += `- \`${s}\` — ${reason}\n`;
md += `\n## Unmapped legacy strings\n\n`;
if (unmapped.size === 0) {
  md += `None — every remaining distinct legacy drug string resolves to a canonical remedy.\n`;
} else {
  md += `These legacy strings did not match any canonical remedy. Add the spelling to the relevant remedy's \`aliases\` in \`content/remedies.json\`, then re-run.\n\n`;
  for (const [s, n] of [...unmapped].sort()) md += `- \`${s}\` (${n} row group(s))\n`;
}

writeFileSync(outPath, md);
console.log(
  `[ingest] ${mapped.length} legacy tuples mapped across ${Object.keys(byCondition).length} conditions; ` +
    `${unmapped.size} unmapped. Wrote content/PROVENANCE.md`,
);
if (unmapped.size > 0) process.exitCode = 1;
